### ISSUE TITLE
nats-rply/nats-req not working

### ISSUE THREAD

**Issue by aricart** [nats-io/nats-box#13] opened 2020-11-10 16:06 UTC
nats-rply/req doesn't seem to be honoring the `-s` flag

```
docker run --network host -ti synadia/jsm:nightly
             _             _               
 _ __   __ _| |_ ___      | |__   _____  __
| '_ \ / _` | __/ __|_____| '_ \ / _ \ \/ /
| | | | (_| | |_\__ \_____| |_) | (_) >  < 
|_| |_|\__,_|\__|___/     |_.__/ \___/_/\_\
                                           
nats-box v0.3.0
docker-desktop:~# nats-rply -s demo.nats.io hello "hi there!"
nats: no servers available for connection
```

```
❯ docker run --network host -ti synadia/jsm:nightly
             _             _               
 _ __   __ _| |_ ___      | |__   _____  __
| '_ \ / _` | __/ __|_____| '_ \ / _ \ \/ /
| | | | (_| | |_\__ \_____| |_) | (_) >  < 
|_| |_|\__,_|\__|___/     |_.__/ \___/_/\_\
                                           
nats-box v0.3.0
docker-desktop:~# nats-req -s demo.nats.io hello ""
nats: no servers available for connection
docker-desktop:~# 
```

**Comment by variadico** [comment] 2020-11-10 23:12
Hm. Yeah, I was able to reproduce as well. Will fix.
For now, here's a workaround:
```
NATS_URL=demo.nats.io nats-rply hello "hi there!"
```

**Comment by variadico** [comment] 2020-11-11 00:51
Hm. nats-box itself seems to work. Not sure how `synadia/jsm` is built.

```
$ docker run --network host -ti synadia/nats-box:latest
             _             _               
 _ __   __ _| |_ ___      | |__   _____  __
| '_ \ / _` | __/ __|_____| '_ \ / _ \ \/ /
| | | | (_| | |_\__ \_____| |_) | (_) >  < 
|_| |_|\__,_|\__|___/     |_.__/ \___/_/\_\
                                           
nats-box v0.4.0
synadiax1:~# nats-rply -s demo.nats.io hello "hi there!"
Listening on [hello nats-box]
```

```

**Comment by aricart** [comment] 2020-11-11 02:11
@ripienaar any info for @variadico

**Comment by ripienaar** [comment] 2020-11-11 02:48
Not sure about those, they are not used for jsm purposes. We need to retire then everywhere in favour of nats. They will not support any new features.

**Comment by variadico** [comment] 2020-12-07 19:44
I think we may be able to close this since we've now deprecated this tool in https://github.com/nats-io/nats-box/pull/14.

**Closed by variadico** 2020-12-07 19:44 UTC
